create table if not exists public.profiles (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    name text not null,
    avatar text,
    settings jsonb not null default '{}'::jsonb,
    sync_revision bigint not null default 0,
    updated_at timestamptz not null default now()
);

create table if not exists public.sync_documents (
    id uuid primary key default gen_random_uuid(),
    profile_id uuid not null references public.profiles(id) on delete cascade,
    document_type text not null,
    document_key text not null,
    payload jsonb not null,
    deleted boolean not null default false,
    revision bigint not null default 0,
    updated_at timestamptz not null default now(),
    unique(profile_id, document_type, document_key)
);

create table if not exists public.sync_events (
    id bigint generated by default as identity primary key,
    profile_id uuid not null references public.profiles(id) on delete cascade,
    entity_type text not null,
    document_key text not null,
    payload jsonb not null,
    deleted boolean not null default false,
    revision bigint not null,
    created_at timestamptz not null default now(),
    unique(profile_id, revision)
);

create index if not exists sync_events_profile_revision_idx on public.sync_events(profile_id, revision);
create index if not exists sync_events_created_at_idx on public.sync_events(created_at);

alter table public.profiles enable row level security;
alter table public.sync_documents enable row level security;
alter table public.sync_events enable row level security;

create policy profiles_owner on public.profiles for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy documents_owner on public.sync_documents for all using (exists (select 1 from public.profiles p where p.id = profile_id and p.user_id = auth.uid())) with check (exists (select 1 from public.profiles p where p.id = profile_id and p.user_id = auth.uid()));
create policy events_owner on public.sync_events for select using (exists (select 1 from public.profiles p where p.id = profile_id and p.user_id = auth.uid()));

create or replace function public.create_default_fluxa_profile()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
    insert into public.profiles (user_id, name) values (new.id, 'Default');
    return new;
end;
$$;

drop trigger if exists on_auth_user_created_fluxa_profile on auth.users;
create trigger on_auth_user_created_fluxa_profile after insert on auth.users for each row execute function public.create_default_fluxa_profile();

alter publication supabase_realtime add table public.sync_events;
