-- Typed Fluxa domain storage.
-- sync_documents/sync_events remain as the wire-compatibility/event cursor layer;
-- these tables keep the actual data in typed, queryable domain rows.

create table if not exists public.library_items (
    id uuid primary key default gen_random_uuid(),
    profile_id uuid not null references public.profiles(id) on delete cascade,
    content_id text not null,
    content_type text not null,
    status text not null default 'watchlist' check (status in ('watchlist', 'completed', 'dropped')),
    name text not null default '',
    poster text,
    poster_shape text not null default 'POSTER',
    background text,
    description text,
    release_info text,
    imdb_rating real,
    genres text[] not null default '{}',
    addon_base_url text,
    added_at bigint not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (profile_id, content_id, content_type)
);

create index if not exists library_items_profile_added_idx
    on public.library_items(profile_id, added_at desc);

create table if not exists public.watch_progress (
    id uuid primary key default gen_random_uuid(),
    profile_id uuid not null references public.profiles(id) on delete cascade,
    content_id text not null,
    content_type text not null,
    video_id text not null default '',
    season integer,
    episode integer,
    position bigint not null default 0,
    duration bigint not null default 0,
    last_watched bigint not null default 0,
    progress_key text not null,
    last_audio_language text,
    last_subtitle_language text,
    last_stream_index integer,
    updated_at timestamptz not null default now(),
    unique (profile_id, progress_key)
);

create index if not exists watch_progress_profile_last_watched_idx
    on public.watch_progress(profile_id, last_watched desc);

create table if not exists public.watch_progress_events (
    event_id bigint generated by default as identity primary key,
    profile_id uuid not null references public.profiles(id) on delete cascade,
    operation text not null check (operation in ('upsert', 'delete')),
    progress_key text not null,
    content_id text not null,
    content_type text not null,
    video_id text not null default '',
    season integer,
    episode integer,
    position bigint not null default 0,
    duration bigint not null default 0,
    last_watched bigint not null default 0,
    created_at timestamptz not null default now()
);

create index if not exists watch_progress_events_profile_cursor_idx
    on public.watch_progress_events(profile_id, event_id);

create table if not exists public.watched_items (
    id uuid primary key default gen_random_uuid(),
    profile_id uuid not null references public.profiles(id) on delete cascade,
    content_id text not null,
    content_type text not null,
    title text not null default '',
    season integer,
    episode integer,
    watched_at bigint not null default 0,
    created_at timestamptz not null default now(),
    unique (profile_id, content_id, content_type, season, episode)
);

create table if not exists public.addons (
    id uuid primary key default gen_random_uuid(),
    profile_id uuid not null references public.profiles(id) on delete cascade,
    url text not null,
    name text,
    enabled boolean not null default true,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (profile_id, url)
);

create table if not exists public.plugins (
    id uuid primary key default gen_random_uuid(),
    profile_id uuid not null references public.profiles(id) on delete cascade,
    url text not null,
    name text,
    enabled boolean not null default true,
    sort_order integer not null default 0,
    repo_type text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (profile_id, url)
);

create table if not exists public.collections (
    id uuid primary key default gen_random_uuid(),
    profile_id uuid not null references public.profiles(id) on delete cascade,
    collections_json jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (profile_id)
);

create table if not exists public.profile_settings_blobs (
    id uuid primary key default gen_random_uuid(),
    profile_id uuid not null references public.profiles(id) on delete cascade,
    platform text not null default 'fluxa',
    settings_json jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (profile_id, platform)
);

alter table public.library_items enable row level security;
alter table public.watch_progress enable row level security;
alter table public.watch_progress_events enable row level security;
alter table public.watched_items enable row level security;
alter table public.addons enable row level security;
alter table public.plugins enable row level security;
alter table public.collections enable row level security;
alter table public.profile_settings_blobs enable row level security;

do $$
declare
    table_name text;
begin
    foreach table_name in array array[
        'library_items', 'watch_progress', 'watch_progress_events',
        'watched_items', 'addons', 'plugins', 'collections',
        'profile_settings_blobs'
    ] loop
        execute format(
            'drop policy if exists %I on public.%I',
            table_name || '_owner', table_name
        );
        execute format(
            'create policy %I on public.%I for all using (exists (select 1 from public.profiles p where p.id = profile_id and p.user_id = auth.uid())) with check (exists (select 1 from public.profiles p where p.id = profile_id and p.user_id = auth.uid()))',
            table_name || '_owner', table_name
        );
    end loop;
end;
$$;

alter publication supabase_realtime add table public.watch_progress_events;
