create table if not exists public.sync_rate_limits (
    profile_id uuid primary key references public.profiles(id) on delete cascade,
    window_started_at timestamptz not null default now(),
    request_count integer not null default 0,
    updated_at timestamptz not null default now()
);

create table if not exists public.sync_audit_log (
    id bigint generated by default as identity primary key,
    profile_id uuid not null references public.profiles(id) on delete cascade,
    entity_type text not null,
    document_key text not null,
    operation text not null check (operation in ('upsert', 'delete', 'throttled')),
    revision bigint not null,
    created_at timestamptz not null default now()
);

create index if not exists sync_audit_log_profile_created_idx
    on public.sync_audit_log(profile_id, created_at desc);

alter table public.sync_rate_limits enable row level security;
alter table public.sync_audit_log enable row level security;

create or replace function public.sync_check_rate_limit(
    p_profile_id uuid,
    p_max_requests integer default 120
) returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
    v_count integer;
begin
    perform pg_advisory_xact_lock(hashtextextended('rate:' || p_profile_id::text, 0));
    insert into public.sync_rate_limits (profile_id, window_started_at, request_count)
    values (p_profile_id, now(), 1)
    on conflict (profile_id) do update set
        window_started_at = case
            when sync_rate_limits.window_started_at <= now() - interval '1 minute' then now()
            else sync_rate_limits.window_started_at
        end,
        request_count = case
            when sync_rate_limits.window_started_at <= now() - interval '1 minute' then 1
            else sync_rate_limits.request_count + 1
        end,
        updated_at = now()
    returning request_count into v_count;
    return v_count <= greatest(p_max_requests, 1);
end;
$$;

revoke all on function public.sync_check_rate_limit(uuid, integer) from public;
revoke all on function public.sync_check_rate_limit(uuid, integer) from anon;
revoke all on function public.sync_check_rate_limit(uuid, integer) from authenticated;
grant execute on function public.sync_check_rate_limit(uuid, integer) to service_role;

-- The wrapper is the only write entry point used by the edge function, so the
-- audit record is committed together with the typed/domain update.
create or replace function public.sync_apply_change_locked(
    p_profile_id uuid,
    p_entity_type text,
    p_document_key text,
    p_payload jsonb,
    p_deleted boolean,
    p_requested_revision bigint
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_revision bigint;
begin
    perform pg_advisory_xact_lock(hashtextextended(p_profile_id::text, 0));
    select greatest(coalesce(sync_revision, 0) + 1, p_requested_revision)
    into v_revision from public.profiles where id = p_profile_id for update;
    if v_revision is null then raise exception 'profile not found'; end if;

    perform public.sync_apply_change(p_profile_id, p_entity_type, p_document_key, p_payload, p_deleted, v_revision);
    insert into public.sync_audit_log(profile_id, entity_type, document_key, operation, revision)
    values (p_profile_id, p_entity_type, p_document_key, case when p_deleted then 'delete' else 'upsert' end, v_revision);
    update public.profiles set sync_revision = greatest(sync_revision, v_revision), updated_at = now() where id = p_profile_id;
    return v_revision;
end;
$$;

revoke all on function public.sync_apply_change_locked(uuid, text, text, jsonb, boolean, bigint) from public;
revoke all on function public.sync_apply_change_locked(uuid, text, text, jsonb, boolean, bigint) from anon;
revoke all on function public.sync_apply_change_locked(uuid, text, text, jsonb, boolean, bigint) from authenticated;
grant execute on function public.sync_apply_change_locked(uuid, text, text, jsonb, boolean, bigint) to service_role;
