create table if not exists public.watched_item_events (
    event_id bigint generated by default as identity primary key,
    profile_id uuid not null references public.profiles(id) on delete cascade,
    operation text not null check (operation in ('upsert', 'delete')),
    content_id text not null,
    content_type text not null,
    season integer,
    episode integer,
    watched_at bigint not null default 0,
    created_at timestamptz not null default now()
);

create index if not exists watched_item_events_profile_cursor_idx
    on public.watched_item_events(profile_id, event_id);

alter table public.watched_item_events enable row level security;
drop policy if exists watched_item_events_owner on public.watched_item_events;
create policy watched_item_events_owner on public.watched_item_events
    for all using (exists (select 1 from public.profiles p where p.id = profile_id and p.user_id = auth.uid()))
    with check (exists (select 1 from public.profiles p where p.id = profile_id and p.user_id = auth.uid()));

create or replace function public.record_watched_item_delta()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
    insert into public.watched_item_events(profile_id, operation, content_id, content_type, season, episode, watched_at)
    values (
        coalesce(new.profile_id, old.profile_id),
        case when tg_op = 'DELETE' then 'delete' else 'upsert' end,
        coalesce(new.content_id, old.content_id),
        coalesce(new.content_type, old.content_type),
        coalesce(new.season, old.season),
        coalesce(new.episode, old.episode),
        coalesce(new.watched_at, old.watched_at, 0)
    );
    if tg_op = 'DELETE' then return old; end if;
    return new;
end;
$$;

drop trigger if exists watched_item_delta_trigger on public.watched_items;
create trigger watched_item_delta_trigger
after insert or update or delete on public.watched_items
for each row execute function public.record_watched_item_delta();
